In [9]:
# Connect Google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


im2latex pickle 변환

In [ ]:
# %cd /content/drive/MyDrive/AI_Project/im2latex-100k

/content/drive/MyDrive/AI_Project/im2latex-100k


In [ ]:
# # 압축 해제 (최초 1회)
# import tarfile
# import os
# from tqdm import tqdm

# # 압축 파일 경로
# tar_path = "formula_images.tar.gz"

# # 압축 해제할 폴더 경로 (예: im2latex-100k/formula_images)
# extract_path = os.path.join("formula_images")

# # 폴더 없으면 생성
# os.makedirs(extract_path, exist_ok=True)

# # 압축 해제
# with tarfile.open(tar_path, "r:gz") as tar:
#     members = tar.getmembers()
#     total_files = len(members)

#     with tqdm(total=total_files, unit='file', desc="압축 해제 진행률") as pbar:
#         for member in members:
#             tar.extract(member, path=extract_path)
#             pbar.update(1)

# print(f"압축 해제 완료: {extract_path}")

In [ ]:
# # 피클 담구기
# import os
# import pickle
# import numpy as np
# from PIL import Image
# from tqdm import tqdm


# # 경로 설정
# IMAGE_FOLDER = "/content/drive/MyDrive/AI_Project/im2latex-100k/formula_images"
# LST_PATH = "/content/drive/MyDrive/AI_Project/im2latex-100k/im2latex_test.lst"
# FORMULAS_PATH = "/content/drive/MyDrive/AI_Project/im2latex-100k/im2latex_formulas.lst"
# OUTPUT_CAPTION = "/content/drive/MyDrive/AI_Project/im2latex-100k/caption.txt"
# OUTPUT_IMAGE = "/content/drive/MyDrive/AI_Project/im2latex-100k/images.pkl"


# # 0. 이미지 리사이즈
# def resize_img_to_height(img, target_height=120):
#     w, h = img.size
#     new_w = int((target_height / h) * w)
#     return img.resize((new_w, target_height), Image.Resampling.LANCZOS)


# # 1. 수식 로딩
# with open(FORMULAS_PATH, "r", encoding="utf-8", errors="ignore") as f:
#     formulas = [line.strip() for line in f]


# # 2. lst 파일 파싱
# pairs = []
# with open(LST_PATH, "r", encoding="utf-8") as f:
#     for line in f:
#         parts = line.strip().split()
#         if len(parts) < 2:
#             continue
#         formula_idx = int(parts[0])
#         image_name = parts[1]
#         pairs.append((formula_idx, image_name))


# # 4. 변환
# image_dict = {}
# caption_lines = []

# for i, (formula_idx, image_name) in enumerate(tqdm(pairs, desc="Processing images")):
#     if i == 100:  # 여기서 100개까지만 처리
#         break

#     img_path = os.path.join(IMAGE_FOLDER, image_name + ".png")
#     if not os.path.exists(img_path):
#         print(f"⚠️ 이미지 없음: {img_path}, 건너뜀")
#         continue

#     try:
#         img = Image.open(img_path).convert("RGBA").convert("L")
#         img_resized = resize_img_to_height(img)
#         img_np = np.array(img_resized, dtype=np.uint8)

#         key_name = image_name + ".jpg"
#         image_dict[key_name] = img_np

#         # formula_tokens = formulas[formula_idx].split()
#         # caption_line = image_name + ".png\t" + " ".join(formula_tokens)
#         # caption_lines.append(caption_line)

#         formula = formulas[formula_idx].strip()
#         tokenized = ' '.join(formula.split())
#         caption_lines.append(f"{key_name}\t{tokenized}")

#     except Exception as e:
#         print(f"[에러] {img_path} 처리 실패: {e}")


# # 5. 저장
# os.makedirs(os.path.dirname(OUTPUT_CAPTION), exist_ok=True)
# os.makedirs(os.path.dirname(OUTPUT_IMAGE), exist_ok=True)

# with open(OUTPUT_IMAGE, "wb") as f:
#     pickle.dump(image_dict, f)

# with open(OUTPUT_CAPTION, "w", encoding="utf-8") as f:
#     f.write("\n".join(caption_lines))

# print("=== Sample captions ===")
# for i, cap in enumerate(caption_lines[:5]):
#     print(f"{i+1}: {cap}")

# # print("\n=== Sample image keys ===")
# # for i, key in enumerate(image_dict.keys()[:5]):
# #     print(f"{i+1}: {key}")

# print("\n✅ 변환 완료! 저장된 이미지 수:", len(image_dict))
# print(f"- 이미지 파일: {OUTPUT_IMAGE}")
# print(f"- 수식 텍스트: {OUTPUT_CAPTION}")

Processing images:   1%|          | 100/10355 [00:05<08:33, 19.95it/s]

=== Sample captions ===
1: 7944775fc9.jpg	i\Delta ^{ab}(q)=\frac{-i\delta ^{ab}}{q^2-\mu ^2+i\varepsilon }
2: 78228211ca.jpg	{\cal A}_{n} : = \langle \prod_{j=1}^{m} S^{k_j}_{-l_j} |\sum_{j=1}^{m} l_j \geq n \rangle\,,
3: 15b9034ba8.jpg	\label{fierep}P_{(2)}^-=\int \beta d\beta d^9p d^8\lambda \Phi(-p,-\lambda)\left(-\frac{p^Ip^I}{2\beta}\right) \Phi(p,\lambda)\,.
4: 6968dfca15.jpg	{\bf E} \rightarrow - c {{\bf B}^{\prime}}\hspace{1.0in} c {\bf B} \rightarrow {{\bf E}^{\prime}}
5: 6cead0df53.jpg	a^{2}=\frac{m\mu }{k^{2}e\lambda ^{2}_{\phi }}\, .

✅ 변환 완료! 저장된 이미지 수: 100
- 이미지 파일: /content/drive/MyDrive/AI_Project/im2latex-100k/images.pkl
- 수식 텍스트: /content/drive/MyDrive/AI_Project/im2latex-100k/caption.txt


CROPME pickle 변환

In [2]:
%cd /content/drive/MyDrive/AI_Project/TAMER/data/crohme

/content/drive/MyDrive/AI_Project/TAMER/data/crohme


In [3]:
import pickle

with open("/content/drive/MyDrive/AI_Project/TAMER/data/crohme/2014/images.pkl", 'rb') as f:
    images = pickle.load(f)

print(f"images type: {type(images)}")
print(f"images keys sample: {list(images.keys())[:5]}")

# 예시로 첫 이미지 배열 확인
first_key = list(images.keys())[0]
print(f"First image key: {first_key}")
print(f"First image shape: {images[first_key].shape}")
print(f"First image dtype: {images[first_key].dtype}")

# 이미지 배열 일부 데이터 출력 (예: 5x5 영역)
print(images[first_key][:5, :5])

images type: <class 'dict'>
images keys sample: ['RIT_2014_293', 'RIT_2014_217', 'RIT_2014_135', 'RIT_2014_248', '509_em_90']
First image key: RIT_2014_293
First image shape: (142, 463)
First image dtype: uint8
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [15]:
# 피클 담구기
import os
import pickle
from PIL import Image
import numpy as np

image_dir = "/content/drive/MyDrive/AI_Project/TAMER/data/cropme/2019"       # printed 이미지 폴더
caption_path = "/content/drive/MyDrive/AI_Project/TAMER/data/crohme/2019/caption.txt"       # caption.txt 파일
output_pkl = "/content/drive/MyDrive/AI_Project/TAMER/data/cropme/2019_images.pkl"   # 테스트용 출력 파일

# 📑 caption.txt 기준으로 이미지 이름 리스트 확보
with open(caption_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

images_dict = {}
missing_count = 0

for line in lines:
    tokens = line.strip().split()
    if not tokens:
        continue

    img_key = tokens[0]                     # 예: RIT_2014_293
    filename = img_key + ".png"             # printed 이미지는 확장자 있는 파일
    img_path = os.path.join(image_dir, filename)

    if not os.path.exists(img_path):
        missing_count += 1
        continue

    # 흑백 이미지로 로딩
    img = Image.open(img_path).convert("L")
    img_np = np.array(img).astype(np.uint8)

    # 크기 제한 (320000 초과시 리사이즈)
    if img_np.shape[0] * img_np.shape[1] > 320000:
        base_height = 256
        h_percent = base_height / img_np.shape[0]
        w_size = int(img_np.shape[1] * h_percent)
        img = img.resize((w_size, base_height), Image.ANTIALIAS)
        img_np = np.array(img).astype(np.uint8)

    images_dict[img_key] = img_np

# ✅ 저장
with open(output_pkl, "wb") as f:
    pickle.dump(images_dict, f)

print(f"[✔] images.pkl saved with {len(images_dict)} images to: {output_pkl}")
print(f"[ℹ️] Number of missed images: {missing_count}")

KeyboardInterrupt: 

In [ ]:
import pickle

with open("/content/drive/MyDrive/AI_Project/TAMER/data/cropme/2019_images.pkl", 'rb') as f:
    images = pickle.load(f)

print(f"images type: {type(images)}")
print(f"images keys sample: {list(images.keys())[:5]}")

# 예시로 첫 이미지 배열 확인
first_key = list(images.keys())[0]
print(f"Total number of images: {len(images)}")
print(f"First image key: {first_key}")
print(f"First image shape: {images[first_key].shape}")
print(f"First image dtype: {images[first_key].dtype}")

# 이미지 배열 일부 데이터 출력 (예: 5x5 영역)
print(images[first_key][:5, :5])